### ISSUE TITLE
NuGet Rebus.CastleWindsor 5.1.0 package depends on Rebus 6.0.0-b6

### ISSUE THREAD

**Issue by AGiorgetti** [rebus-org/Rebus.CastleWindsor#4]
Should it depend on 5.x instead?

**Comment by mookid8000** [comment]
yeah, it probably should.... just a moment, I'll fix it 🙂

**Comment by mookid8000** [comment]
it's fixed in Rebus.Castle.Winsdor 5.1.1, which is on NuGet.org now – thanks for notifying me that the reference was wrong 👍
